default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5

development:
  <<: *default
  username: postgres
  password:
  database: office_space_development

test:
  <<: *default
  username: postgres
  password:
  database: office_space_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
